apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    "mch-imageRepository": "quay.io/open-cluster-management"
    "mch-imageOverridesCM": "hq-image"
spec:
  imagePullSecret: multiclusterhub-operator-pull-secret
  
